services:
  elasticsearch:
    image: elasticsearch:8.14.3
    mem_limit: 1G
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yaml

  kibana:
    image: kibana:8.14.3
    mem_limit: 800M
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.14.3
    mem_limit: 1G
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./configs/logstash/pipelines.yaml:/usr/share/logstash/config/pipelines.yaml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./logs:/var/log/nginx
    depends_on:
          - elasticsearch

    filebeat:
    image: elastic/filebeat:8.14.3
    volumes:
      - ./logs:/var/log/app/
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - logstash
      - elasticsearch
      - kibana

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./logs:/var/log/nginx
